metadata:
  name: churn-agents-webinar
  created: '2025-01-08T19:05:45.327000'
kind: project
status:
  state: online
spec:
  desired_state: online
  source: v3io:///bigdata/churn.zip
  workflows:
  - name: main
    path: src/workflows/train_and_deploy_workflow.py
  owner: nick
  conda: ''
  origin_url: git://github.com/igz-us-sales/churn-agents-webinar.git#refs/heads/master
  params:
    base_image: mlrun/mlrun
    requirements_file: requirements.txt
    force_build: false
    source: v3io:///bigdata/churn.zip
  functions:
  - url: src/functions/data.py
    name: data
    kind: job
    with_repo: true
  - url: src/functions/train.py
    name: train
    kind: job
    image: mlrun/mlrun
    handler: train_model
  - url: src/functions/validate.py
    name: validate
    kind: job
  - url: src/functions/v2_model_server.py
    name: serving
    kind: serving
    image: mlrun/mlrun
  - url: src/functions/v2_model_tester.py
    name: model-server-tester
    kind: job
    handler: model_server_tester
  build:
    base_image: mlrun/mlrun
    with_mlrun: false
    commands:
    - pip install PyGithub==1.59.0 deepchecks==0.18.1 pandera==0.20.3 langchain==0.2.17
      langchain-core==0.2.43 langchain-openai==0.1.25 mlrun==1.7.0
    image: .mlrun-project-image-churn-agents-webinar
  default_image: .mlrun-project-image-churn-agents-webinar
  load_source_on_run: true
